links:
  rails_tutorial:
    home_page: https://www.railstutorial.org/
    help_page: http://www.railstutorial.org/help
    book_page: https://www.railstutorial.org/book

validations:
  name:
    max_length: 50
  email:
    max_length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6
    
signup:
  gravatar:
    url: https://secure.gravatar.com/avatar/
    email: http://gravatar.com/emails

remember_me: 1
per_page: 10
